name: "Slack Notification Action"
description: "Sends or updates a notification in Slack"
author: "Your Name"
inputs:
  slack-token:
    description: "The Slack OAuth token"
    required: true
  slack-channel:
    description: "The Slack channel ID"
    required: true
  status:
    description: "The status of the workflow"
    required: true
  run-id:
    description: "The GitHub Actions run ID"
    required: true
  job-name:
    description: "The GitHub Actions job name"
    required: true
  repository:
    description: "The GitHub repository name"
    required: true
  ref:
    description: "The GitHub ref"
    required: true
  event-name:
    description: "The GitHub event name"
    required: true
  workflow:
    description: "The GitHub workflow name"
    required: true
runs:
  using: "node20"
  main: "../../../dist/src/slack.js"
