name: "Slack Notification Action"
description: "Sends a notification to Slack"
author: "Your Name"
inputs:
  slack-webhook-url:
    description: "The Slack webhook URL"
    required: true
  status:
    description: "The status of the workflow"
    required: true
  run-id:
    description: "The GitHub Actions run ID"
    required: true
  job-name:
    description: "The GitHub Actions job name"
    required: true
runs:
  using: "node20"
  main: "../../../dist/src/slack.js"
