name: "Slack Notification Action"
description: "Sends or updates a notification in Slack"
inputs:
  slack-token:
    description: "The Slack OAuth token"
    required: true
  slack-channel:
    description: "The Slack channel ID"
    required: true
  status:
    description: "The Status of the workflow"
    required: true
  run-id:
    description: "The GitHub Actions run ID"
    required: true
  job-name:
    description: "The GitHub Actions job name"
    required: true
  repository:
    description: "The GitHub Repository name"
    required: true
  ref:
    description: "The GitHub Ref"
    required: true
  event-name:
    description: "The GitHub event name"
    required: true
  workflow:
    description: "The GitHub Workflow name"
    required: true
  slack-thread-ts:
    description: "The Slack Message Timestamp"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: cd slackNotion && npm i
      shell: bash

    - name: Compile TypeScript
      run: cd slackNotion && npm run build
      shell: bash

    - name: Run Script
      run: cd slackNotion && npm run start
      shell: bash
