name: "Slack Notification Action"
description: "Sends or updates a notification in Slack"
author: "roll1226"
inputs:
  SLACK_TOKEN:
    description: "The Slack OAuth token"
    required: true
  SLACK_CHANNEL:
    description: "The Slack channel ID"
    required: true
  STATUS:
    description: "The Status of the workflow"
    required: true
  RUN_ID:
    description: "The GitHub Actions run ID"
    required: true
  JOB_NAME:
    description: "The GitHub Actions job name"
    required: true
  REPOSITORY:
    description: "The GitHub Repository name"
    required: true
  REF:
    description: "The GitHub Ref"
    required: true
  EVENT_NAME:
    description: "The GitHub event name"
    required: true
  WORKFLOW:
    description: "The GitHub Workflow name"
    required: true
  SLACK_THREAD_TS:
    description: "The Slack Message Timestamp"
    required: false
outputs:
  SLACK_THREAD_TS:
    description: "Slack Timestamp"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: cd slackNotion && npm ci
      shell: bash

    - name: Compile TypeScript
      run: cd slackNotion && npm run build
      shell: bash

    - name: Run Script
      run: cd slackNotion && npm run start
      shell: bash
