name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        type: choice
        description: Version bump type
        options:
          - MAJOR
          - MINOR
          - PATCH
      date:
        type: string
        description: リリース日
        default: $(date +'%Y-%m-%d')

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.date }}
      JSON_FILE_PATH: package.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --global user.email "tset@example.com"
          git config --global user.name "example"
      - name: Create release branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH_NAME }}
      - name: Update version
        run: |
          version_bump_type=${{ github.event.inputs.version_bump_type }}
          current_version=$(jq -r .version ${{ env.JSON_FILE_PATH }})
          IFS='.' read -r -a version_parts <<< "$current_version"
          case $version_bump_type in
            MAJOR)
              version_parts[0]=$((version_parts[0] + 1))
              version_parts[1]=0
              version_parts[2]=0
              ;;
            MINOR)
              version_parts[1]=$((version_parts[1] + 1))
              version_parts[2]=0
              ;;
            PATCH)
              version_parts[2]=$((version_parts[2] + 1))
              ;;
          esac
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          jq ".version = \"$new_version\"" ${{ env.JSON_FILE_PATH }} > ${{ env.JSON_FILE_PATH }}.tmp
          mv ${{ env.JSON_FILE_PATH }}.tmp ${{ env.JSON_FILE_PATH }}
          git add ${{ env.JSON_FILE_PATH }}
          git commit -m "chore: bump version to $new_version"
          git push origin ${{ env.RELEASE_BRANCH_NAME }}
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y
      - name: Create PR for release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh pr create --base main --head ${{ env.RELEASE_BRANCH_NAME }} --title "Release ${{ env.RELEASE_BRANCH_NAME }}" --body "This is an automated release PR."
# name: Create Release Branch

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   create-release-branch:
#     runs-on: ubuntu-latest

#     steps:
#       # リポジトリをチェックアウト
#       - name: Check out repository
#         uses: actions/checkout@v2

#       # 現在のバージョンを取得
#       - name: Get Current Version
#         id: version
#         run: |
#           # バージョン番号を取得 (例: package.json)
#           VERSION=$(jq -r .version package.json)
#           echo "version=$VERSION" >> $GITHUB_ENV

#       # リリース用のブランチを作成してプッシュ
#       - name: Create and Push Release Branch
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"

#           # リリースブランチを作成
#           git checkout -b release/$version

#           # 空のコミットを作成 (リリースブランチの存在を確実にするため)
#           git commit --allow-empty -m "chore: create release branch for version $version"

#           # リリースブランチをプッシュ
#           git push origin release/$version
