name: Restrict base branch
on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  restrict-base-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: agaroot-technologies/action-restrict-base-branch@v1.0.2
        with:
          rules: |
            main <- release/*
            release/* <- feature/**/* fix/**/* update/**/* refactor/**/* doc/**/* deps/**/*
            feature/**/* <- feature/**/*
            feature/**/* <- update/**/*
            update/**/* <- update/**/*
            update/**/* <- feature/**/*
