name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify_test_start:
    runs-on: ubuntu-latest
    outputs:
      slackThreadTs: ${{ steps.notify_test_start.outputs.slack-thread-ts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Send Slack notification (test start)
        id: notify_test_start
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: "start"
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          event-name: ${{ github.event_name }}
          workflow: ${{ github.workflow }}
          slack_thread_ts: ""

  test:
    runs-on: ubuntu-latest
    needs: notify_test_start
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Send Slack notification (test success)
        if: success()
        id: notify_test_success
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: "success"
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          event-name: ${{ github.event_name }}
          workflow: ${{ github.workflow }}
          slack_thread_ts: ${{ needs.notify_test_start.outputs.slackThreadTs }}

      - name: Send Slack notification (test failure)
        if: failure()
        id: notify_test_failure
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: "failure"
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          event-name: ${{ github.event_name }}
          workflow: ${{ github.workflow }}
          slack_thread_ts: ${{ needs.notify_test_start.outputs.slackThreadTs }}

      - name: Send Slack notification (test cancelled)
        if: cancelled()
        id: notify_test_cancelled
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: "cancelled"
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          event-name: ${{ github.event_name }}
          workflow: ${{ github.workflow }}
          slack_thread_ts: ${{ needs.notify_test_start.outputs.slackThreadTs }}
