name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Send Slack notification (start)
        id: notify_start
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: 'start'
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}

      - name: Run some job
        run: npm install
        continue-on-error: true

      - name: Send Slack notification (success)
        if: success()
        id: notify_success
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: 'success'
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          slack_thread_ts: ${{ steps.notify_start.outputs.slack-thread-ts }}
        env:
          SLACK_THREAD_TS: ${{ steps.notify_start.outputs.slack-thread-ts }}

      - name: Send Slack notification (failure)
        if: failure()
        id: notify_failure
        uses: ./actions/yml/slack
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: 'failure'
          run-id: ${{ github.run_id }}
          job-name: ${{ github.job }}
          slack_thread_ts: ${{ steps.notify_start.outputs.slack-thread-ts }}
        env:
          SLACK_THREAD_TS: ${{ steps.notify_start.outputs.slack-thread-ts }}
